### ISSUE TITLE
eBPF need licese ?failed to start.

### ISSUE THREAD

**Issue by pythonmandev** [Gui774ume/ebpfkit-monitor#1]
sudo ebpfkit-monitor start
FATAL[2022-06-05T12:23:40Z] failed to start ebpfkit-monitor: failed to setup eBPF manager: failed to init eBPF manager: load license: missing license section 
I use strace to trace the syscall and info,but it did not get the license alert before.I've search the google and find nothing about it.

4351  execve("/usr/bin/ebpfkit-monitor", ["ebpfkit-monitor", "start"], 0x7fffb3caa7a0 /* 24 vars */) = 0
4351  access("/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
4351  openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
4351  newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=23241, ...}, AT_EMPTY_PATH) = 0
4351  openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
4351  newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2216304, ...}, AT_EMPTY_PATH) = 0
4351  openat(AT_FDCWD, "/sys/kernel/mm/transparent_hugepage/hpage_pmd_size", O_RDONLY) = 3
4351  openat(AT_FDCWD, "/proc/stat", O_RDONLY|O_CLOEXEC) = 3
4351  newfstatat(AT_FDCWD, "/usr/bin/getconf", {st_mode=S_IFREG|0755, st_size=35112, ...}, 0) = 0
4351  openat(AT_FDCWD, "/dev/null", O_RDONLY|O_CLOEXEC) = 3
4358  execve("/usr/bin/getconf", ["/usr/bin/getconf", "CLK_TCK"], 0xc00009cf70 /* 24 vars */) = 0
4358  access("/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
4358  openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
4358  newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=23241, ...}, AT_EMPTY_PATH) = 0
4358  openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
4358  newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2216304, ...}, AT_EMPTY_PATH) = 0
4358  openat(AT_FDCWD, "/usr/lib/locale/C.utf8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = 3
4358  newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=353616, ...}, AT_EMPTY_PATH) = 0
4358  openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", O_RDONLY) = 3
4358  newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=27002, ...}, AT_EMPTY_PATH) = 0
4358  openat(AT_FDCWD, "/usr/lib/locale/C.utf8/LC_MESSAGES", O_RDONLY|O_CLOEXEC) = 3
4358  newfstatat(3, "", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_EMPTY_PATH) = 0
4358  openat(AT_FDCWD, "/usr/lib/locale/C.utf8/LC_MESSAGES/SYS_LC_MESSAGES", O_RDONLY|O_CLOEXEC) = 3
4358  newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=48, ...}, AT_EMPTY_PATH) = 0
4358  newfstatat(1, "", {st_mode=S_IFIFO|0600, st_size=0, ...}, AT_EMPTY_PATH) = 0
4358  +++ exited with 0 +++
4353  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4358, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
4351  newfstatat(AT_FDCWD, ".", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
4351  newfstatat(AT_FDCWD, "/root", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
4351  openat(AT_FDCWD, "/proc/net/psched", O_RDONLY|O_CLOEXEC) = 3
4351  openat(AT_FDCWD, "/proc/stat", O_RDONLY|O_CLOEXEC) = 3
4351  readlinkat(AT_FDCWD, "/proc/self/exe", "/usr/bin/ebpfkit-monitor", 128) = 24
4351  openat(AT_FDCWD, "/etc/os-release", O_RDONLY|O_CLOEXEC) = 3
4351  openat(AT_FDCWD, "/proc/kallsyms", O_RDONLY|O_CLOEXEC) = 3
4351  --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=4351, si_uid=0} ---
4351  openat(AT_FDCWD, "/etc/localtime", O_RDONLY) = 3
4357  +++ exited with 1 +++

**Comment by pythonmandev** [comment]
The ~/go/pkg/mod/github.com/!data!dog/ebpf@v0.0.0-20210201234834-a101c2fadd02/elf_reader.go file contain the info.

**Comment by flairekq** [comment]
> The ~/go/pkg/mod/github.com/!data!dog/ebpf@v0.0.0-20210201234834-a101c2fadd02/elf_reader.go file contain the info.

Hi, where do u find the file mentioned?

**Comment by pythonmandev** [comment]
> > The ~/go/pkg/mod/github.com/!data!dog/ebpf@v0.0.0-20210201234834-a101c2fadd02/elf_reader.go file contain the info.
> 
> Hi, where do u find the file mentioned?

I find it in the GOPATH of golang.

**Comment by flairekq** [comment]
> > > The ~/go/pkg/mod/github.com/!data!dog/ebpf@v0.0.0-20210201234834-a101c2fadd02/elf_reader.go file contain the info.
> > 
> > 
> > Hi, where do u find the file mentioned?
> 
> I find it in the GOPATH of golang.

oh thanks found it! what am i supposed to do with the information there?

**Comment by pythonmandev** [comment]
> > > > The ~/go/pkg/mod/github.com/!data!dog/ebpf@v0.0.0-20210201234834-a101c2fadd02/elf_reader.go file contain the info.
> > > 
> > > 
> > > Hi, where do u find the file mentioned?
> > 
> > 
> > I find it in the GOPATH of golang.
> 
> oh thanks found it! what am i supposed to do with the information there?

Would you like to fix it,thank you!

**Comment by flairekq** [comment]
> > > > > The ~/go/pkg/mod/github.com/!data!dog/ebpf@v0.0.0-20210201234834-a101c2fadd02/elf_reader.go file contain the info.
> > > > 
> > > > 
> > > > Hi, where do u find the file mentioned?
> > > 
> > > 
> > > I find it in the GOPATH of golang.
> > 
> > 
> > oh thanks found it! what am i supposed to do with the information there?
> 
> Would you like to fix it,thank you!

oh wait u mean u haven't found a fix to this issue yet?

**Comment by pythonmandev** [comment]
> > > > > > The ~/go/pkg/mod/github.com/!data!dog/ebpf@v0.0.0-20210201234834-a101c2fadd02/elf_reader.go file contain the info.
> > > > > 
> > > > > 
> > > > > Hi, where do u find the file mentioned?
> > > > 
> > > > 
> > > > I find it in the GOPATH of golang.
> > > 
> > > 
> > > oh thanks found it! what am i supposed to do with the information there?
> > 
> > 
> > Would you like to fix it,thank you!
> 
> oh wait u mean u haven't found a fix to this issue yet?

Yes,I dont know how to fix it :(

**Comment by flairekq** [comment]
> > > > > > > The ~/go/pkg/mod/github.com/!data!dog/ebpf@v0.0.0-20210201234834-a101c2fadd02/elf_reader.go file contain the info.
> > > > > > 
> > > > > > 
> > > > > > Hi, where do u find the file mentioned?
> > > > > 
> > > > > 
> > > > > I find it in the GOPATH of golang.
> > > > 
> > > > 
> > > > oh thanks found it! what am i supposed to do with the information there?
> > > 
> > > 
> > > Would you like to fix it,thank you!
> > 
> > 
> > oh wait u mean u haven't found a fix to this issue yet?
> 
> Yes,I dont know how to fix it :(

same :( i was exploring ebpfkit-monitor to see if it works but faced the same issue as u

**Comment by pythonmandev** [comment]
> > > > > > > > The ~/go/pkg/mod/github.com/!data!dog/ebpf@v0.0.0-20210201234834-a101c2fadd02/elf_reader.go file contain the info.
> > > > > > > 
> > > > > > > 
> > > > > > > Hi, where do u find the file mentioned?
> > > > > > 
> > > > > > 
> > > > > > I find it in the GOPATH of golang.
> > > > > 
> > > > > 
> > > > > oh thanks found it! what am i supposed to do with the information there?
> > > > 
> > > > 
> > > > Would you like to fix it,thank you!
> > > 
> > > 
> > > oh wait u mean u haven't found a fix to this issue yet?
> > 
> > 
> > Yes,I dont know how to fix it :(
> 
> same :( i was exploring ebpfkit-monitor to see if it works but faced the same issue as u

I thought you're the owner of ebpfkit-monitor by mistake.We wait for @Gui774ume to fix it together,good luck.

**Comment by Gui774ume** [comment]
Hey there 👋🏻 

Can you provide more information about your environment ? Are you sure the compilation was successful ?

The error you describe usually happens when the compilation fails and the eBPF programs are not compiled properly ?
Note that the compilation of the golang binary might be successful even if the compilatoin of the eBPF programs failed ... TL;DR look for the compilation logs.

I pushed a tiny fix for the compilation to work on 5.13+ kernels, depending on your environment it might help.

**Comment by pythonmandev** [comment]
> Hey there 👋🏻
> 
> Can you provide more information about your environment ? Are you sure the compilation was successful ?
> 
> The error you describe usually happens when the compilation fails and the eBPF programs are not compiled properly. Note that the compilation of the golang binary might be successful even if the compilatoin of the eBPF programs failed ... TL;DR look for the compilation logs.

Thanks!You're right,I've found the error,I will try to fix it.

**Comment by pythonmandev** [comment]
It could be run in the ubuntu 20.04 with the latest kernel.
root@ubuntu:~/ebpfkit-monitor# make run
sudo ./bin/ebpfkit-monitor start --allowed-processes "/usr/sbin/bpftool"
INFO[2022-06-18T06:05:20Z] ebpfkit-monitor is now running !             
root@ubuntu:~/ebpfkit-monitor# uname -r
5.4.0-120-generic
Thank you @Gui774ume 
cc @flairekq

**Comment by Gui774ume** [comment]
Glad to hear you made it work !
Feel free to submit a PR if you found a bug, I'll be happy to merge it.
Closing for now, reopen if need be :)
